/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/records/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get play records
         * @description Retrieve play records for a user based on scope (b50, best, all, all-charts)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Scope (b50, best, all, all-charts) */
                    scope?: string;
                    /** @description Underflow for b50 */
                    underflow?: number;
                    /** @description Page size */
                    page_size?: number;
                    /** @description Page index */
                    page_index?: number;
                    /** @description Sort by (rating, score, record_time, etc.) */
                    sort_by?: string;
                    /** @description Order (desc or asc) */
                    order?: string;
                };
                header?: never;
                path: {
                    /** @description Username */
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.PlayRecordResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload play records
         * @description Batch upload play records for a user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Username */
                    username: string;
                };
                cookie?: never;
            };
            /** @description Play records upload info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.BatchCreatePlayRecordRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.PlayRecord"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{username}/chart/{chart_addr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get play records for a specific chart
         * @description Retrieve play records for a user scoped to a specific chart. chart_addr can be numeric chart_id or wiki_id:difficulty (e.g. felys:massive).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Scope (best, all) */
                    scope?: string;
                    /** @description Page size (scope=all only) */
                    page_size?: number;
                    /** @description Page index (scope=all only) */
                    page_index?: number;
                    /** @description Sort by (rating, score, record_time) */
                    sort_by?: string;
                    /** @description Order (desc or asc) */
                    order?: string;
                };
                header?: never;
                path: {
                    /** @description Username */
                    username: string;
                    /** @description Chart address (numeric chart_id or wiki_id:difficulty) */
                    chart_addr: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.PlayRecordResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{username}/song/{song_addr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get play records for a specific song
         * @description Retrieve play records for a user scoped to a specific song. song_addr can be numeric song_id or wiki_id.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Scope (best, all) */
                    scope?: string;
                    /** @description Page size (scope=all only) */
                    page_size?: number;
                    /** @description Page index (scope=all only) */
                    page_index?: number;
                    /** @description Sort by (rating, score, record_time) */
                    sort_by?: string;
                    /** @description Order (desc or asc) */
                    order?: string;
                };
                header?: never;
                path: {
                    /** @description Username */
                    username: string;
                    /** @description Song address (numeric song_id or wiki_id) */
                    song_addr: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.PlayRecordResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all charts
         * @description Retrieve a list of all charts with their details
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ChartInfo"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        /**
         * Update an existing song
         * @description Update song details and its charts (Admin only)
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Song update info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.UpdateSongRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.ChartInfo"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single song info
         * @description Retrieve detailed information about a single song by ID
         */
        get: {
            parameters: {
                query?: {
                    /** @description Source (prp or wiki) */
                    src?: string;
                };
                header?: never;
                path: {
                    /** @description Song ID */
                    song_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Song"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Authenticate user and return JWT token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description Username */
                        username: string;
                        /** @description Password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Token"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Get the profile of the currently authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        /**
         * Update current user info
         * @description Update the profile of the currently authenticated user
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User update info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.User"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password
         * @description Change the current user's password
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Password change info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/upload-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh upload token
         * @description Generate a new upload token for the current user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.UploadToken"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Create a new user account
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User registration info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.UserPublic"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset user password (Admin only)
         * @description Reset a user's password by admin
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Password reset info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["request.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "model.Chart": {
            /** @example massive */
            difficulty?: components["schemas"]["model.Difficulty"];
            fitting_level?: number;
            id?: number;
            level?: number;
            level_design?: string;
            notes?: number;
            /** @example Alt Artist */
            override_artist?: string;
            /** @example Cover_alt.jpg */
            override_cover?: string;
            /** @example Alt Title */
            override_title?: string;
            /** @example 2.0.0 */
            override_version?: string;
            song?: components["schemas"]["model.Song"];
            song_id?: number;
        };
        "model.ChartInfo": {
            /** @example First Album */
            album?: string;
            /** @example Artist Name */
            artist: string;
            /** @example false */
            b15?: boolean;
            /** @example 180 */
            bpm?: string;
            /** @example Cover_d3d3d3.jpg */
            cover?: string;
            /** @example massive */
            difficulty?: components["schemas"]["model.Difficulty"];
            /** @example 13.4 */
            fitting_level?: number;
            /** @example Pop */
            genre?: string;
            /** @example 10 */
            id?: number;
            /** @example Artist */
            illustrator?: string;
            /** @example 2:30 */
            length?: string;
            /** @example 13.2 */
            level?: number;
            /** @example Designer */
            level_design?: string;
            /** @example 850 */
            notes?: number;
            /** @example 1 */
            song_id?: number;
            /** @example Song Title */
            title: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example w123 */
            wiki_id: string;
        };
        "model.ChartInfoSimple": {
            b15?: boolean;
            cover?: string;
            difficulty?: components["schemas"]["model.Difficulty"];
            fitting_level?: number;
            id?: number;
            level?: number;
            song_id?: number;
            title?: string;
            version?: string;
            wiki_id?: string;
        };
        "model.ChartInput": {
            /**
             * @example massive
             * @enum {unknown}
             */
            difficulty: "detected" | "invaded" | "massive" | "reboot";
            /** @example 14.5 */
            level: number;
            /** @example Designer */
            level_design?: string;
            /** @example 1000 */
            notes: number;
            /** @example Alt Artist */
            override_artist?: string;
            /** @example Cover_alt.jpg */
            override_cover?: string;
            /** @example Alt Title */
            override_title?: string;
            /** @example 2.0.0 */
            override_version?: string;
        };
        /** @enum {string} */
        "model.Difficulty": "detected" | "invaded" | "massive" | "reboot";
        "model.PlayRecord": {
            chart?: components["schemas"]["model.Chart"];
            /** @example 1 */
            chart_id: number;
            id?: number;
            rating?: number;
            record_time?: string;
            /** @example 1000000 */
            score: number;
            username?: string;
        };
        "model.PlayRecordBase": {
            /** @example 1 */
            chart_id: number;
            /** @example 1000000 */
            score: number;
        };
        "model.PlayRecordInfo": {
            chart?: components["schemas"]["model.ChartInfoSimple"];
            id?: number;
            rating?: number;
            record_time?: string;
            score?: number;
        };
        "model.PlayRecordResponse": {
            nickname?: string;
            records?: components["schemas"]["model.PlayRecordInfo"][];
            total?: number;
            username?: string;
        };
        "model.Response": {
            error?: string;
            message?: string;
        };
        "model.Song": {
            /** @example First Album */
            album?: string;
            /** @example Artist Name */
            artist: string;
            /** @example false */
            b15?: boolean;
            /** @example 180 */
            bpm?: string;
            charts?: components["schemas"]["model.Chart"][];
            /** @example Cover_d3d3d3.jpg */
            cover?: string;
            /** @example Pop */
            genre?: string;
            id?: number;
            /** @example Artist */
            illustrator?: string;
            /** @example 2:30 */
            length?: string;
            /** @example Song Title */
            title: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example w123 */
            wiki_id: string;
        };
        "model.Token": {
            access_token?: string;
            /** @example Bearer */
            token_type?: string;
        };
        "model.UploadToken": {
            upload_token?: string;
        };
        "model.User": {
            /** @example act_001 */
            account?: string;
            /** @example 1001 */
            account_number?: number;
            /** @example false */
            anonymous_probe?: boolean;
            /** @example user@example.com */
            email: string;
            id?: number;
            /** @example true */
            is_active?: boolean;
            /** @example false */
            is_admin?: boolean;
            /** @example 小明 */
            nickname?: string;
            /** @example 12345678 */
            qq_account?: string;
            /** @example token_xyz */
            upload_token?: string;
            /** @example user123 */
            username: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            uuid?: string;
        };
        "model.UserPublic": {
            /** @example act_001 */
            account?: string;
            /** @example 1001 */
            account_number?: number;
            /** @example false */
            anonymous_probe?: boolean;
            /** @example user@example.com */
            email?: string;
            /** @example 1 */
            id?: number;
            /** @example 小明 */
            nickname?: string;
            /** @example 12345678 */
            qq_account?: string;
            /** @example user123 */
            username?: string;
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            uuid?: string;
        };
        "request.BatchCreatePlayRecordRequest": {
            is_replace?: boolean;
            play_records: components["schemas"]["model.PlayRecordBase"][];
            upload_token?: string;
        };
        "request.ChangePasswordRequest": {
            /** @example newpass456 */
            new_password: string;
            /** @example oldpass123 */
            old_password: string;
        };
        "request.CreateSongRequest": {
            /** @example First Album */
            album?: string;
            /** @example Artist Name */
            artist: string;
            /** @example false */
            b15?: boolean;
            /** @example 180 */
            bpm?: string;
            charts: components["schemas"]["model.ChartInput"][];
            /** @example Cover_d3d3d3.jpg */
            cover?: string;
            /** @example Pop */
            genre?: string;
            /** @example Artist */
            illustrator?: string;
            /** @example 2:30 */
            length?: string;
            /** @example Song Title */
            title: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example w123 */
            wiki_id: string;
        };
        "request.CreateUserRequest": {
            /** @example user@example.com */
            email: string;
            /** @example 小明 */
            nickname?: string;
            /** @example secret123 */
            password: string;
            /** @example user123 */
            username: string;
        };
        "request.ResetPasswordRequest": {
            /** @example newpass456 */
            new_password: string;
            /** @example targetuser */
            username: string;
        };
        "request.UpdateSongRequest": {
            /** @example First Album */
            album?: string;
            /** @example Artist Name */
            artist: string;
            /** @example false */
            b15?: boolean;
            /** @example 180 */
            bpm?: string;
            charts: components["schemas"]["model.ChartInput"][];
            /** @example Cover_d3d3d3.jpg */
            cover?: string;
            /** @example Pop */
            genre?: string;
            id: number;
            /** @example Artist */
            illustrator?: string;
            /** @example 2:30 */
            length?: string;
            /** @example Song Title */
            title: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example w123 */
            wiki_id: string;
        };
        "request.UpdateUserRequest": {
            account?: string;
            account_number?: number;
            anonymous_probe?: boolean;
            nickname?: string;
            qq_account?: string;
            uuid?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
